/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: ['class', '[data-theme="dark"]'],
  corePlugins: {
    preflight: false,
  },
  theme: {
    extend: {
      colors: {
        brand: {
          DEFAULT: '#10b981',
          dark: '#059669',
          glow: 'rgba(16, 185, 129, 0.12)',
          border: 'rgba(16, 185, 129, 0.25)',
        },
        // CSS variable-based colors for theme support
        th: {
          bg: 'var(--color-bg)',
          'bg-alt': 'var(--color-bg-alt)',
          surface: 'var(--color-surface)',
          'surface-hover': 'var(--color-surface-hover)',
          text: 'var(--color-text)',
          muted: 'var(--color-text-muted)',
          border: 'var(--color-border)',
          'border-hover': 'var(--color-border-hover)',
          primary: 'var(--color-primary)',
          'primary-dark': 'var(--color-primary-dark)',
          'primary-glow': 'var(--color-primary-glow)',
          'primary-border': 'var(--color-primary-border)',
          success: 'var(--color-success)',
          error: 'var(--color-error)',
          'error-glow': 'var(--color-error-glow)',
          'btn-text': 'var(--color-btn-text)',
          'footer-dim': 'var(--color-footer-dim)',
          'footer-dimmer': 'var(--color-footer-dimmer)',
          'phone-bg': 'var(--color-phone-bg)',
          'phone-border': 'var(--color-phone-border)',
          'sms-received-bg': 'var(--color-sms-received-bg)',
          'sms-received-border': 'var(--color-sms-received-border)',
          'dot-bg': 'var(--color-dot-bg)',
          'dot-hover': 'var(--color-dot-hover)',
        },
      },
      fontFamily: {
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Helvetica Neue', 'sans-serif'],
      },
      maxWidth: {
        page: '1120px',
        'content-narrow': '660px',
        'content-wide': '1060px',
        'pricing': '1000px',
        'cards': '950px',
        'compare': '820px',
        'seo': '720px',
        'form': '680px',
        'form-inner': '580px',
        'form-btn': '560px',
        'desc': '500px',
        'sb-desc': '460px',
        'flow-col': '340px',
        'cmp-card': '380px',
        'cta-btn': '480px',
      },
      width: {
        'phone': '280px',
        'cta-icon': '56px',
        'flow-icon': '52px',
        'cmp-icon': '44px',
        'avatar': '40px',
        'step-num': '36px',
        'step-circle': '28px',
        'cmp-badge': '24px',
        'notch': '80px',
      },
      height: {
        'phone-screen': '340px',
        'stat-divider': '40px',
      },
      spacing: {
        'arrow': '36px',
      },
      borderRadius: {
        'phone': '32px',
        'card': '20px',
        'card-inner': '18px',
        'flow': '16px',
        'input': '14px',
        'pill': '20px',
        'step': '9px',
      },
      fontSize: {
        'hero': ['clamp(2.4rem, 5vw, 4rem)', { lineHeight: '1.08', letterSpacing: '-0.04em', fontWeight: '900' }],
        'section': ['clamp(1.8rem, 3.5vw, 2.6rem)', { lineHeight: '1.1', letterSpacing: '-0.035em', fontWeight: '900' }],
        'section-sm': ['clamp(1.8rem, 3vw, 2.4rem)', { lineHeight: '1.1', letterSpacing: '-0.035em', fontWeight: '900' }],
        'price': ['2.75rem', { lineHeight: '1', letterSpacing: '-0.04em', fontWeight: '900' }],
        'stat': ['2rem', { lineHeight: '1', letterSpacing: '-0.03em', fontWeight: '900' }],
      },
      animation: {
        'glow-pulse': 'ctaPulse 3s ease-in-out infinite',
        'hero-glow': 'heroGlow 8s ease-in-out infinite alternate',
        'gradient-shift': 'gradientShift 4s ease infinite',
        'spin-fast': 'spin 0.6s linear infinite',
        'shake': 'shake 0.4s ease-in-out',
      },
      keyframes: {
        ctaPulse: {
          '0%, 100%': { boxShadow: '0 0 20px rgba(16,185,129,0.25), 0 0 60px rgba(16,185,129,0.1)' },
          '50%': { boxShadow: '0 0 30px rgba(16,185,129,0.4), 0 0 80px rgba(16,185,129,0.15)' },
        },
        heroGlow: {
          '0%': { opacity: '0.7', transform: 'scale(1) translateY(0)' },
          '50%': { opacity: '1', transform: 'scale(1.03) translateY(-8px)' },
          '100%': { opacity: '0.8', transform: 'scale(0.98) translateY(4px)' },
        },
        gradientShift: {
          '0%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
          '100%': { backgroundPosition: '0% 50%' },
        },
        shake: {
          '0%, 100%': { transform: 'translateX(0)' },
          '20%, 60%': { transform: 'translateX(-4px)' },
          '40%, 80%': { transform: 'translateX(4px)' },
        },
        flowSlideIn: {
          from: { opacity: '0', transform: 'translateX(-32px)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
        flowSlideUp: {
          from: { opacity: '0', transform: 'translateY(24px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
      },
      transitionProperty: {
        'card': 'border-color, box-shadow, transform',
      },
    },
  },
  plugins: [],
};
